sudo: false
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
    - app/bower_components
before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - gem update --system
  - gem install sass
before_script:
  - 'phantomjs --version'
  - 'firefox --version'
  - 'npm install -g gulp-cli'
  - 'npm install -g karma-cli'
  - 'npm install -g bower'
  - 'bower install'
script:
  - 'npm run-script test'
